language: php

php:
  - 7.3

before_script:
  - pip install --user codecov
  - composer self-update
  - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - codecov